### ISSUE TITLE
Enable 2FA on Frappe Cloud sign in

### ISSUE THREAD

**Issue by sapna-kcs** [frappe/press#1663]
To sign in on Frappe Cloud to hosts all servers, an option should be available via FC Settings to enable 2FA for secure Login.

**Comment by marination** [comment]
Bump! Its a valid concern that the app FC hosts support 2FA, but the admin that can essentially drop benches is not protected by the same.
@netchampfaris @rutwikhdev @balamurali27 tagging for visibility. Can we see this on the roadmap anytime soon? It has been kind of a deal breaker for one of our clients as well.

**Comment by joshuarestivo** [comment]
Surprising that this hasn't gotten any attention. This is is glaring issue that needs resolution sooner, rather than later. It is the one thing that is preventing us from more broadly adopting Frappe Cloud. Password-only login in 2024 is amateur hour and not something that any serious organization can tolerate. Many have adopted policies forbidding it.
