### ISSUE TITLE
Team member permission

### ISSUE THREAD

**Issue by NEW-MTC-ERP1** [frappe/press#1895]
Hello

One of my clients wanted access to his server on FC, so when I tried giving him such access; I faced serious issues:
1- He can drop the server and rename it, also the sites and benches with full control, which is critically serious although, I gave him minimum access control:
![image](https://github.com/frappe/press/assets/114433956/b4258593-c90b-44ba-b6a5-2d5545e4040a)

2- He has access to notifications which is related to sites, benches and servers not related to them, and they don't have access to.

Is there any way that you're getting granular permission on these actions.

**Comment by mohsinalimat** [comment]
Also need features like each page section wise permission set in team member.

**Comment by BreadGenie** [comment]
Granular permissions won't be coming back, as it was dropped due to several issues, which made things harder for us, as bugs weren't easily debug-able, the design of the system wasn't great (storing the action method in db etc). Which was why we chose to do a simpler permission system based on roles.

> 1- He can drop the server and rename it, also the sites and benches with full control, which is critically serious although, I gave him minimum access control

He can control the server but he shouldn't be able to control the benches and sites with just the server permissions alone. See if you've allowed him any sites or benches in the list. BTW the screenshot you've shared controls server/site/bench creation and not access to them. Those are controlled in a separate list. Refer https://frappecloud.com/docs/role-permissions

> 2- He has access to notifications which is related to sites, benches and servers not related to them, and they don't have access to.

This is a bug and should be filtered out based on the user's access. Will fix it asap

**Comment by BreadGenie** [comment]
Notifications are now applied with permissions #1926 
Closing this for now
