### ISSUE TITLE
Temporary volume when restoring large sites (10GB?)

### ISSUE THREAD

**Issue by balamurali27** [frappe/press#1932]
Downloading backup files creates additional storage requirement (2x in best case scenario). These files could be put in temporary volume. Alternatively, s3 could be mounted on the server as well.

**Comment by arunmathaisk** [comment]
The problem mentioned in the issue is, while restoring the agent downloads the file from S3, performs restore, and then deletes the downloaded files.

But as it's not resizable, the user has to pay for the additional storage.

In context to the above, I mean when you perform backups that will expand the EBS anyway. And is it wrong to say the size of backups( compressed) will be ~ restore backup size?

So what is the point of optimizing for a leaner restore when you expand the EBS anyway while backup?
Just delete all existing backups first before restoring ( as all backups are there in S3 anyway)

**Comment by balamurali27** [comment]
Makes sense as from v14 onwards db backup is not uncompressed on app server
