### ISSUE TITLE
Specifying Release Group in Site Plan broken?

### ISSUE THREAD

**Issue by casesolved-co-uk** [frappe/press#2059]
A newly added feature has the wrong logic I think.

The Site Plan has a table for specifying allowed Release Groups
But the query logic does this:

https://github.com/frappe/press/blob/badb892f6188ad84b4b938f61628d6333da5eb93/press/api/site.py#L520

`name` should be `in` the allowed list (not `not in`) ?
Unless you're trying to find the pool of Release Groups that have not already been assigned to any site plans? In which case shouldn't it be called Reserved Release Groups in the UI?

There doesn't seem to be any logic to ensure a new site gets assigned to one of the listed Release Groups?

@tanmoysrt

**Comment by tanmoysrt** [comment]
Hi @casesolved-co-uk 

Actually, on the backend there are tiny benches against each available public bench version. Like-

| Public bench | Custom bench |
| ---- | ---- |
| Version 15 | Version 15 Tiny |
| Nightly | Nightly Tiny |

So, in the frontend apis we send only the public bench's version list (Nightly, Version 15, Version 14) to select. So from frontend it send a public bench/release group info while calling site creation api.

Based on the plan selected, we change it to tiny one on the backend side.
https://github.com/frappe/press/blob/badb892f6188ad84b4b938f61628d6333da5eb93/press/press/doctype/site/site.py#L1988-L2066

It was done to keep the ui simple, so that people don't need to choose tiny release group/bench version separately.
