### ISSUE TITLE
Add User to Proxy: Error response from daemon: No such container: ssh

### ISSUE THREAD

**Issue by niyazrazak** [frappe/press#2155]
![image](https://github.com/user-attachments/assets/5488222a-3f4e-4201-96de-ffe9a72bcd86)
![image](https://github.com/user-attachments/assets/a5af5e7d-e848-4f1b-8988-b3a8e6f6bfc7)

![image](https://github.com/user-attachments/assets/77f82fff-4ea8-45b1-818d-1018c85b8737)
![image](https://github.com/user-attachments/assets/3333f7d6-45f7-470f-ab33-53e82500f670)

Any solution for this?

**Comment by raugustos1** [comment]
How u solve this?

**Comment by niyazrazak** [comment]
create ssh certificate authority and run setup proxysql in proyserver

**Comment by g0ha1** [comment]
> create ssh certificate authority and run setup proxysql in proyserver

Did you mean "Setup SSH Proxy"? After this ansible play also fails, because the required image (ssh?) is not in the registry and into ansible play "setup ssh proxy" pass empty variable: "docker_image": null. What action needs to be performed to have the ssh image appear in the registry?

**Comment by harizan01** [comment]
I resolved the issue by adding the frappe user to the docker group. The root cause was that the frappe user lacked the necessary permissions to interact with Docker.

Even after assigning the appropriate permissions, it may not take effect immediately. In such cases, a service restart is required for the changes to apply properly.

To fix this:

Add the frappe user to the docker group on the App Server.

Restart the necessary services or agent on the App Server.

On the Proxy Server, restart the following supervisor services:

"sudo supervisorctl restart agent:web agent:redis agent:worker-0"

This ensures that both permission changes and agent services are reloaded correctly.

**Comment by karacaismail** [comment]
What are your proposed solutions?
