### ISSUE TITLE
revamp: slow query analyzer and index suggestion

### ISSUE THREAD

**Issue by tanmoysrt** [frappe/press#2358]

**Comment by ankush** [comment]
I wrote one such "index suggestion" report in FW: https://github.com/frappe/frappe/pull/26433

My hypothesis was that >90% of queries were just missing one simple single index. Which in my experience has been true. This is because most missing indexes come from custom field or custom app where not much thought has been put onto performance of certain queries :sweat_smile: 

Anyway here's something to explore:
- Some simple semantic analysis of query. E.g. `x > y` is a range query and might not benefit even if it's indexed. This will reduce false suggestions.
- Enable collecting statistics (some overhead), with root access OR user access to their own DB, we can write better "optimizers". 

Some good papers to read:

- An Efficient, Cost-Driven Index Selection Tool for Microsoft SQL Server - https://15799.courses.cs.cmu.edu/spring2022/papers/03-indexes1/chaudhuri-vldb1997.pdf
- AutoAdmin "What IF" - https://dl.acm.org/doi/10.1145/276304.276337
- AutoAdmin from SQL Server - https://www.microsoft.com/en-us/research/wp-content/uploads/2006/01/deb.pdf 
- A Decade of self-tuning databases - https://15799.courses.cs.cmu.edu/spring2022/papers/01-background/p3-chaudhuri.pdf

**Comment by ankush** [comment]
And the GOAT ofcourse: https://15799.courses.cs.cmu.edu/spring2022/

**Comment by tanmoysrt** [comment]
@ankush 
We exposed that index suggestion report for the end user a few months ago. The implementation is causing issues.
That's why I am just refactoring that part and moving some logic on the agent side to quickly find the suggested indexes of multiple queries.
Currently, I am not refactoring the analyzer's code. Will try to make that better after exploring this stuff more.
